name = "dag-admin-server"

server = {
    port = 8000
    contextPath = "dag-admin-server"
}

cookie.domain = [
    "localhost"
    "jack007.top"
]

database = {
    jdbcUrl = NOT-SET
    username = NOT-SET
    password = NO-NEED
    driverClassName = "org.postgresql.Driver"
    maximumPoolSize = 10
    minimumIdle = 1
    autoCommit = false
    readOnly = false
}

flyway = {
    locations = ["classpath:db/migration"]
    baselineVersion = "1"
    baselineDescription = "Baseline"
    baselineOnMigrate = true
    table = "flyway_schema_history"
    defaultSchema = "public"
    placeholders = {
        owner_suffix = app_ro
    }
}

cookie = {
    name = "dag-admin-server-jwt"
    valueType = "JWT"
}

security = {
    whiteList = [
        "/**/openapi.json",
        "/**/api.html"
    ]
}

jwt = {
    issuer = "dag-task-scheduler"
    publicKeyLocation = "file:NOT-SET"
    privateKeyLocation = "file:NOT-SET"
    ttl = "7d"
}

users = []

query = {
    dateFormat = "yyyy-MM-dd"
    timestampFormat = "yyyy-MM-dd HH:mm:ss.SSS"
    timeFormat = "HH:mm:ss.SSS"
}
