---
host_helper_root: /opt/hosthelper
host_helper_user: hosthelper
host_helper_group: hosthelper
host_helper_release_config_dir: /etc/host-helper/release-config
host_helper_config_source_dir: /etc/host-helper/config

