name = "dag-task-server"

server = {
    port = 8000
    contextPath = "dag-scheduler-server"
}


# The database config
database = {
    jdbcUrl = NOT-SET
    username = NOT-SET
    password = NO-NEED
    driverClassName = "org.postgresql.Driver"
    maximumPoolSize = 10
    minimumIdle = 1
    autoCommit = false
    readOnly = false
}

# security settings
security = {
    whiteList = [
        "/**/openapi.json",
        "/**/api.html",
        "/dag-scheduler-server/api/v1/scheduler/register",
        "/dag-scheduler-server/api/v1/scheduler/unregister",
    ]
}

# jwt settings
jwt = {
    issuer = "dag-scheduler-server",
    audience = "dag-agent",
    publicKeyLocation = "file:NOT-SET",
    privateKeyLocation = "file:NOT-SET",
    ttl = "30d"
}


# customize the output
query = {
    dateFormat = "yyyy-MM-dd"
    timestampFormat = "yyyy-MM-dd HH:mm:ss.SSS"
    timeFormat = "HH:mm:ss.SSS"
}

