name = "dag-task-server"

server = {
    port = 8000
    contextPath = "dag-task-server"
}

# all host helper instances with given env classification
cookie.domain = [
    "localhost"
    "jack007.top"
]

# The database config
database = {
    jdbcUrl = NOT-SET
    username = NOT-SET
    password = NO-NEED
    driverClassName = "org.postgresql.Driver"
    maximumPoolSize = 10
    minimumIdle = 1
    autoCommit = false
    readOnly = false
}
# the flyway configuration
flyway = {
    locations = ["classpath:db/migration"]
    baselineVersion = "1"
    baselineDescription = "Baseline"
    baselineOnMigrate = true
    table = "flyway_schema_history"
    defaultSchema = "public"
    placeholders = {
        owner_suffix = app_ro
    }
}


## the cookie name
cookie = {
    name = "dag-task-server-jwt"
    valueType = "JWT"
}

# security settings
security = {
    whiteList = [
        "^/openapi.json",
        "^/api.html",
    ]
}

# jwt settings
jwt = {
    issuer = "dag-task-scheduler"
    publicKeyLocation = "file:NOT-SET"
    privateKeyLocation = "file:NOT-SET"
    ttl = "1h"
}

## The config user list
users = []


# customize the output
query = {
    dateFormat = "yyyy-MM-dd"
    timestampFormat = "yyyy-MM-dd HH:mm:ss.SSS"
    timeFormat = "HH:mm:ss.SSS"
}

