import type { Workflow, Execution, Agent, DashboardStats, TrendData, AgentWhitelist } from "@/types";

export const mockWorkflows: Workflow[] = [
  {
    id: "wf-001",
    key: "etl-daily",
    name: "Daily ETL Pipeline",
    description: "Extract, transform and load daily data from multiple sources into the data warehouse",
    version: "2.1.0",
    active: true,
    dagDefinition: {
      nodes: [
        { id: "extract", type: "default", position: { x: 100, y: 100 }, data: { label: "Extract Data", type: "task", config: { source: "postgresql" } } },
        { id: "validate", type: "default", position: { x: 300, y: 100 }, data: { label: "Validate Schema", type: "task", config: {} } },
        { id: "transform", type: "default", position: { x: 500, y: 100 }, data: { label: "Transform Data", type: "task", config: {} } },
        { id: "load", type: "default", position: { x: 700, y: 100 }, data: { label: "Load to DW", type: "database", config: { target: "snowflake" } } },
        { id: "notify", type: "default", position: { x: 900, y: 100 }, data: { label: "Send Notification", type: "task", config: {} } },
      ],
      edges: [
        { id: "e1", source: "extract", target: "validate" },
        { id: "e2", source: "validate", target: "transform" },
        { id: "e3", source: "transform", target: "load" },
        { id: "e4", source: "load", target: "notify" },
      ],
    },
    parameterSchema: { fields: [] },
    tags: ["etl", "data-pipeline", "production"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-06T12:00:00Z",
    lastExecution: { id: "exec-001", status: "running", startedAt: "2024-01-07T10:30:00Z" },
    executionCount: 1425,
    successRate: 97.2,
  },
  {
    id: "wf-002",
    key: "backup-weekly",
    name: "Weekly Database Backup",
    description: "Perform full database backup every Sunday at 2 AM",
    version: "1.5.0",
    active: true,
    dagDefinition: {
      nodes: [
        { id: "check-disk", type: "default", position: { x: 100, y: 100 }, data: { label: "Check Disk Space", type: "shell", config: { command: "df -h" } } },
        { id: "dump-db", type: "default", position: { x: 300, y: 100 }, data: { label: "Dump Database", type: "database", config: {} } },
        { id: "compress", type: "default", position: { x: 500, y: 100 }, data: { label: "Compress Backup", type: "task", config: {} } },
        { id: "upload", type: "default", position: { x: 700, y: 100 }, data: { label: "Upload to S3", type: "task", config: {} } },
        { id: "cleanup", type: "default", position: { x: 900, y: 100 }, data: { label: "Cleanup Old Backups", type: "shell", config: { command: "find /backup -mtime +30 -delete" } } },
      ],
      edges: [
        { id: "e1", source: "check-disk", target: "dump-db" },
        { id: "e2", source: "dump-db", target: "compress" },
        { id: "e3", source: "compress", target: "upload" },
        { id: "e4", source: "upload", target: "cleanup" },
      ],
    },
    parameterSchema: { fields: [] },
    tags: ["backup", "database", "maintenance"],
    createdAt: "2024-01-02T00:00:00Z",
    updatedAt: "2024-01-05T08:00:00Z",
    lastExecution: { id: "exec-002", status: "success", startedAt: "2024-01-07T09:00:00Z", endedAt: "2024-01-07T09:15:00Z", duration: 900000 },
    executionCount: 52,
    successRate: 98.1,
  },
  {
    id: "wf-003",
    key: "ml-training",
    name: "ML Model Training",
    description: "Train machine learning models using the latest dataset",
    version: "3.0.0",
    active: true,
    dagDefinition: {
      nodes: [
        { id: "prepare-data", type: "default", position: { x: 100, y: 100 }, data: { label: "Prepare Dataset", type: "python", config: { script: "prepare_data.py" } } },
        { id: "preprocess", type: "default", position: { x: 300, y: 100 }, data: { label: "Preprocess", type: "python", config: { script: "preprocess.py" } } },
        { id: "split", type: "default", position: { x: 500, y: 50 }, data: { label: "Split Data", type: "task", config: {} } },
        { id: "train", type: "default", position: { x: 700, y: 50 }, data: { label: "Train Model", type: "python", config: { script: "train.py" } } },
        { id: "evaluate", type: "default", position: { x: 700, y: 150 }, data: { label: "Evaluate", type: "python", config: { script: "evaluate.py" } } },
        { id: "deploy", type: "default", position: { x: 900, y: 100 }, data: { label: "Deploy Model", type: "task", config: {} } },
      ],
      edges: [
        { id: "e1", source: "prepare-data", target: "preprocess" },
        { id: "e2", source: "preprocess", target: "split" },
        { id: "e3", source: "split", target: "train" },
        { id: "e4", source: "split", target: "evaluate" },
        { id: "e5", source: "train", target: "deploy" },
        { id: "e6", source: "evaluate", target: "deploy" },
      ],
    },
    parameterSchema: { fields: [] },
    tags: ["ml", "ai", "training"],
    createdAt: "2024-01-03T00:00:00Z",
    updatedAt: "2024-01-06T15:00:00Z",
    lastExecution: { id: "exec-003", status: "failed", startedAt: "2024-01-07T08:00:00Z", endedAt: "2024-01-07T08:45:00Z", duration: 2700000 },
    executionCount: 128,
    successRate: 85.5,
  },
  {
    id: "wf-004",
    key: "data-cleanup",
    name: "Data Cleanup Task",
    description: "Clean up old and unused data from the system",
    version: "1.0.0",
    active: false,
    dagDefinition: {
      nodes: [
        { id: "identify", type: "default", position: { x: 100, y: 100 }, data: { label: "Identify Old Data", type: "database", config: { query: "SELECT * FROM logs WHERE created_at < NOW() - INTERVAL '90 days'" } } },
        { id: "archive", type: "default", position: { x: 300, y: 100 }, data: { label: "Archive to S3", type: "task", config: {} } },
        { id: "verify", type: "default", position: { x: 500, y: 100 }, data: { label: "Verify Archive", type: "task", config: {} } },
        { id: "delete", type: "default", position: { x: 700, y: 100 }, data: { label: "Delete Old Data", type: "database", config: { query: "DELETE FROM logs WHERE created_at < NOW() - INTERVAL '90 days'" } } },
      ],
      edges: [
        { id: "e1", source: "identify", target: "archive" },
        { id: "e2", source: "archive", target: "verify" },
        { id: "e3", source: "verify", target: "delete" },
      ],
    },
    parameterSchema: { fields: [] },
    tags: ["cleanup", "maintenance"],
    createdAt: "2024-01-04T00:00:00Z",
    updatedAt: "2024-01-04T10:00:00Z",
    executionCount: 24,
    successRate: 100,
  },
  {
    id: "wf-005",
    key: "email-notifications",
    name: "Email Notification System",
    description: "Send automated email notifications to users",
    version: "1.2.0",
    active: true,
    dagDefinition: {
      nodes: [
        { id: "fetch-users", type: "default", position: { x: 100, y: 100 }, data: { label: "Fetch Users", type: "database", config: { query: "SELECT email, name FROM users WHERE notifications_enabled = true" } } },
        { id: "render", type: "default", position: { x: 300, y: 100 }, data: { label: "Render Templates", type: "task", config: {} } },
        { id: "send", type: "default", position: { x: 500, y: 100 }, data: { label: "Send Emails", type: "task", config: {} } },
        { id: "track", type: "default", position: { x: 700, y: 100 }, data: { label: "Track Delivery", type: "database", config: { query: "INSERT INTO email_logs ..." } } },
      ],
      edges: [
        { id: "e1", source: "fetch-users", target: "render" },
        { id: "e2", source: "render", target: "send" },
        { id: "e3", source: "send", target: "track" },
      ],
    },
    parameterSchema: { fields: [] },
    tags: ["notification", "email", "production"],
    createdAt: "2024-01-05T00:00:00Z",
    updatedAt: "2024-01-06T09:00:00Z",
    lastExecution: { id: "exec-008", status: "success", startedAt: "2024-01-07T10:00:00Z", endedAt: "2024-01-07T10:02:00Z", duration: 120000 },
    executionCount: 8760,
    successRate: 99.8,
  },
  {
    id: "wf-006",
    key: "user-sync",
    name: "User Data Synchronization",
    description: "Synchronize user data across multiple services",
    version: "2.0.0",
    active: true,
    dagDefinition: {
      nodes: [
        { id: "read-users", type: "default", position: { x: 100, y: 100 }, data: { label: "Read from CRM", type: "database", config: {} } },
        { id: "compare", type: "default", position: { x: 300, y: 100 }, data: { label: "Compare with Auth", type: "task", config: {} } },
        { id: "decision", type: "default", position: { x: 500, y: 100 }, data: { label: "Has Changes?", type: "decision", config: {} } },
        { id: "update-auth", type: "default", position: { x: 700, y: 50 }, data: { label: "Update Auth Service", type: "task", config: {} } },
        { id: "update-billing", type: "default", position: { x: 700, y: 150 }, data: { label: "Update Billing", type: "task", config: {} } },
        { id: "log-sync", type: "default", position: { x: 900, y: 100 }, data: { label: "Log Sync Results", type: "database", config: {} } },
      ],
      edges: [
        { id: "e1", source: "read-users", target: "compare" },
        { id: "e2", source: "compare", target: "decision" },
        { id: "e3", source: "decision", target: "update-auth" },
        { id: "e4", source: "decision", target: "update-billing" },
        { id: "e5", source: "update-auth", target: "log-sync" },
        { id: "e6", source: "update-billing", target: "log-sync" },
      ],
    },
    parameterSchema: { fields: [] },
    tags: ["sync", "user", "integration"],
    createdAt: "2024-01-06T00:00:00Z",
    updatedAt: "2024-01-07T06:00:00Z",
    lastExecution: { id: "exec-009", status: "pending", startedAt: "2024-01-07T11:00:00Z" },
    executionCount: 336,
    successRate: 96.5,
  },
  {
    id: "wf-007",
    key: "log-analysis",
    name: "Log Analysis Pipeline",
    description: "Analyze system logs and generate reports",
    version: "1.8.0",
    active: true,
    dagDefinition: {
      nodes: [
        { id: "collect", type: "default", position: { x: 100, y: 100 }, data: { label: "Collect Logs", type: "shell", config: { command: "cat /var/log/app/*.log" } } },
        { id: "parse", type: "default", position: { x: 300, y: 100 }, data: { label: "Parse & Filter", type: "python", config: { script: "parse_logs.py" } } },
        { id: "analyze", type: "default", position: { x: 500, y: 100 }, data: { label: "Analyze Patterns", type: "python", config: { script: "analyze.py" } } },
        { id: "generate-report", type: "default", position: { x: 700, y: 100 }, data: { label: "Generate Report", type: "task", config: {} } },
        { id: "send-alert", type: "default", position: { x: 900, y: 100 }, data: { label: "Send Alert if Needed", type: "task", config: {} } },
      ],
      edges: [
        { id: "e1", source: "collect", target: "parse" },
        { id: "e2", source: "parse", target: "analyze" },
        { id: "e3", source: "analyze", target: "generate-report" },
        { id: "e4", source: "generate-report", target: "send-alert" },
      ],
    },
    parameterSchema: { fields: [] },
    tags: ["logs", "analysis", "monitoring"],
    createdAt: "2024-01-07T00:00:00Z",
    updatedAt: "2024-01-07T08:00:00Z",
    lastExecution: { id: "exec-010", status: "success", startedAt: "2024-01-07T07:00:00Z", endedAt: "2024-01-07T07:30:00Z", duration: 1800000 },
    executionCount: 168,
    successRate: 94.8,
  },
  {
    id: "wf-008",
    key: "api-health-check",
    name: "API Health Check",
    description: "Monitor API endpoints health status",
    version: "1.0.0",
    active: true,
    dagDefinition: {
      nodes: [
        { id: "check-auth", type: "default", position: { x: 100, y: 50 }, data: { label: "Check Auth API", type: "task", config: {} } },
        { id: "check-user", type: "default", position: { x: 100, y: 150 }, data: { label: "Check User API", type: "task", config: {} } },
        { id: "check-payment", type: "default", position: { x: 100, y: 250 }, data: { label: "Check Payment API", type: "task", config: {} } },
        { id: "aggregate", type: "default", position: { x: 350, y: 150 }, data: { label: "Aggregate Results", type: "task", config: {} } },
        { id: "decide", type: "default", position: { x: 600, y: 150 }, data: { label: "All Healthy?", type: "decision", config: {} } },
        { id: "alert", type: "default", position: { x: 850, y: 100 }, data: { label: "Send Alert", type: "task", config: {} } },
        { id: "report", type: "default", position: { x: 850, y: 200 }, data: { label: "Update Status Page", type: "task", config: {} } },
      ],
      edges: [
        { id: "e1", source: "check-auth", target: "aggregate" },
        { id: "e2", source: "check-user", target: "aggregate" },
        { id: "e3", source: "check-payment", target: "aggregate" },
        { id: "e4", source: "aggregate", target: "decide" },
        { id: "e5", source: "decide", target: "alert" },
        { id: "e6", source: "decide", target: "report" },
      ],
    },
    parameterSchema: { fields: [] },
    tags: ["monitoring", "api", "health"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-07T00:00:00Z",
    lastExecution: { id: "exec-011", status: "running", startedAt: "2024-01-07T10:45:00Z" },
    executionCount: 10080,
    successRate: 99.9,
  },
];
export const mockExecutions: Execution[] = [
  { id: "exec-001", workflowId: "wf-001", workflowKey: "etl-daily", workflowName: "Daily ETL Pipeline", version: "2.1.0", status: "running", triggerType: "scheduled", startedAt: "2024-01-07T10:30:00Z", progress: 65 },
  { id: "exec-002", workflowId: "wf-002", workflowKey: "backup-weekly", workflowName: "Weekly Database Backup", version: "1.5.0", status: "success", triggerType: "manual", startedAt: "2024-01-07T09:00:00Z", endedAt: "2024-01-07T09:15:00Z", duration: 900000 },
  { id: "exec-003", workflowId: "wf-003", workflowKey: "ml-training", workflowName: "ML Model Training", version: "3.0.0", status: "failed", triggerType: "api", startedAt: "2024-01-07T08:00:00Z", endedAt: "2024-01-07T08:45:00Z", duration: 2700000, errorMessage: "GPU memory insufficient" },
  { id: "exec-004", workflowId: "wf-001", workflowKey: "etl-daily", workflowName: "Daily ETL Pipeline", version: "2.1.0", status: "success", triggerType: "scheduled", startedAt: "2024-01-06T10:30:00Z", endedAt: "2024-01-06T10:45:00Z", duration: 900000 },
  { id: "exec-005", workflowId: "wf-004", workflowKey: "data-cleanup", workflowName: "Data Cleanup Task", version: "1.0.0", status: "pending", triggerType: "scheduled", startedAt: "2024-01-07T11:00:00Z" },
  { id: "exec-006", workflowId: "wf-002", workflowKey: "backup-weekly", workflowName: "Weekly Database Backup", version: "1.5.0", status: "cancelled", triggerType: "manual", startedAt: "2024-01-07T07:00:00Z", endedAt: "2024-01-07T07:05:00Z", duration: 300000 },
  { id: "exec-007", workflowId: "wf-003", workflowKey: "ml-training", workflowName: "ML Model Training", version: "3.0.0", status: "retrying", triggerType: "api", startedAt: "2024-01-07T06:00:00Z" },
  { id: "exec-008", workflowId: "wf-005", workflowKey: "email-notifications", workflowName: "Email Notification System", version: "1.2.0", status: "success", triggerType: "scheduled", startedAt: "2024-01-07T10:00:00Z", endedAt: "2024-01-07T10:02:00Z", duration: 120000 },
  { id: "exec-009", workflowId: "wf-006", workflowKey: "user-sync", workflowName: "User Data Synchronization", version: "2.0.0", status: "pending", triggerType: "scheduled", startedAt: "2024-01-07T11:00:00Z" },
  { id: "exec-010", workflowId: "wf-007", workflowKey: "log-analysis", workflowName: "Log Analysis Pipeline", version: "1.8.0", status: "success", triggerType: "scheduled", startedAt: "2024-01-07T07:00:00Z", endedAt: "2024-01-07T07:30:00Z", duration: 1800000 },
  { id: "exec-011", workflowId: "wf-008", workflowKey: "api-health-check", workflowName: "API Health Check", version: "1.0.0", status: "running", triggerType: "scheduled", startedAt: "2024-01-07T10:45:00Z", progress: 30 },
  { id: "exec-012", workflowId: "wf-001", workflowKey: "etl-daily", workflowName: "Daily ETL Pipeline", version: "2.1.0", status: "success", triggerType: "scheduled", startedAt: "2024-01-05T10:30:00Z", endedAt: "2024-01-05T10:42:00Z", duration: 720000 },
  { id: "exec-013", workflowId: "wf-003", workflowKey: "ml-training", workflowName: "ML Model Training", version: "3.0.0", status: "success", triggerType: "api", startedAt: "2024-01-06T06:00:00Z", endedAt: "2024-01-06T09:00:00Z", duration: 10800000 },
  { id: "exec-014", workflowId: "wf-005", workflowKey: "email-notifications", workflowName: "Email Notification System", version: "1.2.0", status: "failed", triggerType: "scheduled", startedAt: "2024-01-06T10:00:00Z", endedAt: "2024-01-06T10:01:00Z", duration: 60000, errorMessage: "SMTP connection timeout" },
  { id: "exec-015", workflowId: "wf-002", workflowKey: "backup-weekly", workflowName: "Weekly Database Backup", version: "1.5.0", status: "success", triggerType: "scheduled", startedAt: "2024-01-06T02:00:00Z", endedAt: "2024-01-06T02:18:00Z", duration: 1080000 },
];
export const mockAgents: Agent[] = [
  { id: "agent-001", name: "worker-01", host: "192.168.1.101", status: "online", version: "2.1.0", capabilities: ["docker", "python", "shell"], currentTasks: 3, maxTasks: 8, cpuUsage: 45, memoryUsage: 62, diskUsage: 78, lastHeartbeat: "2024-01-07T10:59:00Z", tags: ["primary", "docker"] },
  { id: "agent-002", name: "worker-02", host: "192.168.1.102", status: "busy", version: "2.1.0", capabilities: ["docker", "python", "shell", "gpu"], currentTasks: 8, maxTasks: 8, cpuUsage: 92, memoryUsage: 88, diskUsage: 65, lastHeartbeat: "2024-01-07T10:58:00Z", tags: ["gpu", "ml"] },
  { id: "agent-003", name: "worker-03", host: "192.168.1.103", status: "online", version: "2.0.5", capabilities: ["shell", "java"], currentTasks: 2, maxTasks: 6, cpuUsage: 35, memoryUsage: 48, diskUsage: 82, lastHeartbeat: "2024-01-07T10:57:00Z", tags: ["java", "backend"] },
  { id: "agent-004", name: "gpu-01", host: "192.168.1.104", status: "offline", version: "2.1.0", capabilities: ["docker", "python", "gpu"], currentTasks: 0, maxTasks: 4, cpuUsage: 0, memoryUsage: 0, diskUsage: 45, lastHeartbeat: "2024-01-07T08:30:00Z", tags: ["gpu", "ml"] },
  { id: "agent-005", name: "worker-04", host: "192.168.1.105", status: "online", version: "2.1.0", capabilities: ["docker", "shell", "database"], currentTasks: 1, maxTasks: 10, cpuUsage: 28, memoryUsage: 55, diskUsage: 70, lastHeartbeat: "2024-01-07T10:59:30Z", tags: ["database", "primary"] },
];
export const mockDashboardStats: DashboardStats = {
  totalWorkflows: 8,
  activeWorkflows: 7,
  totalExecutions: 1523,
  runningExecutions: 3,
  successRate: 96.8,
  avgDuration: 450000,
  onlineAgents: 3,
  totalAgents: 5,
  failedExecutions24h: 12,
};

export const mockTrends: TrendData[] = [
  { date: "2024-01-01", executions: 180, successful: 175, failed: 5, avgDuration: 420000 },
  { date: "2024-01-02", executions: 195, successful: 188, failed: 7, avgDuration: 380000 },
  { date: "2024-01-03", executions: 210, successful: 203, failed: 7, avgDuration: 410000 },
  { date: "2024-01-04", executions: 185, successful: 178, failed: 7, avgDuration: 390000 },
  { date: "2024-01-05", executions: 220, successful: 214, failed: 6, avgDuration: 460000 },
  { date: "2024-01-06", executions: 245, successful: 237, failed: 8, avgDuration: 480000 },
  { date: "2024-01-07", executions: 288, successful: 275, failed: 13, avgDuration: 520000 },
];

export const mockAgentWhitelists: AgentWhitelist[] = [
  {
    id: 1,
    ipSegment: "127.0.0.1/32",
    description: "Allow localhost registration",
    enabled: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: 2,
    agentId: "whitelist-agent-001",
    description: "Allow specific agent by ID",
    enabled: true,
    createdAt: "2024-01-02T00:00:00Z",
    updatedAt: "2024-01-02T00:00:00Z",
  },
  {
    id: 3,
    ipSegment: "192.168.1.0/24",
    description: "Allow local network",
    enabled: false,
    createdAt: "2024-01-03T00:00:00Z",
    updatedAt: "2024-01-05T00:00:00Z",
  },
];