#!/bin/bash
#
# Helper script: creates output files in the current working directory.
# Used to test working directory setup and artifact generation.
#
# Arguments:
#   $1 - number of files to create (default: 3)
#   $2 - content prefix (default: "output")

FILE_COUNT="${1:-3}"
PREFIX="${2:-output}"

echo "Creating $FILE_COUNT files in $(pwd)..."

for ((i=1; i<=FILE_COUNT; i++))
do
    FILENAME="${PREFIX}_${i}.txt"
    echo "File generated by write_files.sh" > "$FILENAME"
    echo "Index: $i" >> "$FILENAME"
    echo "Timestamp: $(date -Iseconds 2>/dev/null || date "+%Y-%m-%dT%H:%M:%S")" >> "$FILENAME"
    echo "PID: $$" >> "$FILENAME"
    echo "Created: $FILENAME"
done

echo ""
echo "=== Files in working directory ==="
ls -la *.txt 2>/dev/null || echo "(no .txt files found)"

echo ""
echo "✅ File creation complete"
