# MuServer configuration for DAG Task Agent
muserver {
  # HTTP server port
  port = 8080
  host = "0.0.0.0"
  contextPath = "/agent"
  # Idle timeout in milliseconds
  idleTimeout = 30000
}

## The DAG agent configuration
dag-agent {
    agentUrl =  "NOT-SET"
    dagServerUrl = "NOT-SET"
    agentId = "foo"
    autoRegister = true
    maxConcurrentTasks = 4
    maxPendingTasks = 100
    supportedExecutionKeys = [
        "top.ilovemyhome.dagtask.agent.execution.EchoExecution"
        "top.ilovemyhome.dagtask.agent.execution.LongRunningExecution"
    ]
    deadLetterPersistencePath = "G:\\temp\\dag-task\\"
}

