# MuServer configuration for DAG Task Agent
muserver {
    # HTTP server port
    port = 10000
    host = "0.0.0.0"
    contextPath = "/agent"
    # Idle timeout in milliseconds
    idleTimeout = 30000
}

## The DAG agent configuration
dag-agent {
    agentUrl = "NOT-SET"
    agentName = "agent-01"
    dagServerUrl = "NOT-SET"
    agentId = "NOT-SET"
    autoRegister = true
    generateToken = true
    maxConcurrentTasks = 4
    maxPendingTasks = 2000
    supportedExecutionKeys = [
        "top.ilovemyhome.dagtask.agent.execution.EchoExecution"
    ]
}

